name: dart_queue
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.7 <3.0.0'

dependencies:
  uuid: ^3.0.7
  synchronized: ^3.0.1
  hive: ^2.2.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
